---
cinnamon_config:
  - key: /org/cinnamon/active-display-scale
    value: 2
  - key: /org/cinnamon/alttab-switcher-delay
    value: 100
  - key: /org/cinnamon/desktop-effects
    value: 'false'
  - key: /org/cinnamon/desktop-effects-on-dialogs
    value: 'false'
  - key: /org/cinnamon/desktop-effects-on-menus
    value: 'false'
  # Set Caps Lock as layout switch button
  - key: /org/cinnamon/desktop/input-sources/xkb-options
    value: "['grp:caps_toggle', 'caps:none']"
  - key: /org/cinnamon/show-media-keys-osd
    value: "'small'"
  - key: /org/cinnamon/startup-animation
    value: 'false'
  - key: /org/cinnamon/desktop/interface/clock-show-date
    value: 'true'
  - key: /org/cinnamon/desktop/interface/clock-use-24h
    value: 'true'
  - key: /org/cinnamon/desktop/interface/first-day-of-week
    value: 1
  - key: /org/cinnamon/desktop/interface/gtk-theme
    value: "'Adwaita'"
  - key: /org/cinnamon/desktop/interface/icon-theme
    value: "'Faenza'"
  - key: /org/cinnamon/desktop/interface/cursor-size
    value: 24
  - key: /org/cinnamon/desktop/interface/cursor-theme
    value: "'capitaine-cursors-light'"
  - key: /org/cinnamon/desktop/interface/keyboard-layout-prefer-variant-names
    value: 'true'
  - key: /org/cinnamon/desktop/interface/keyboard-layout-use-upper
    value: 'true'
  - key: /org/cinnamon/desktop/privacy/recent-files-max-age
    value: 180
  - key: /org/cinnamon/desktop/privacy/remember-recent-files
    value: 'true'
  - key: /org/cinnamon/desktop/wm/preferences/action-scroll-titlebar
    value: "'shade'"
  - key: /org/cinnamon/desktop/wm/preferences/min-window-opacity
    value: 30
  - key: /org/cinnamon/desktop/wm/preferences/titlebar-font
    value: "'Sans Bold 8'"
  # controls how the Muffin window manager (Cinnamon's compositor) synchronizes window drawing with monitor's refresh rate
  - key: /org/cinnamon/muffin/sync-method
    value: "'swap_throttling'"
  - key: /org/cinnamon/muffin/desktop-effects
    value: 'false'
  - key: /org/cinnamon/muffin/unredirect-fullscreen-windows
    value: 'true'
#  - key: /org/cinnamon/settings-daemon/peripherals/mouse/custom-acceleration
#    value: 'true'
#  - key: /org/cinnamon/settings-daemon/peripherals/mouse/motion-acceleration
#    value: 1.0
#  - key: /org/cinnamon/settings-daemon/peripherals/mouse/motion-threshold
#    value: 1
#  - key: /org/cinnamon/settings-daemon/peripherals/touchpad/custom-acceleration
#    value: 'true'
#  - key: /org/cinnamon/settings-daemon/peripherals/touchpad/custom-threshold
#    value: 'false'
#  - key: /org/cinnamon/settings-daemon/peripherals/touchpad/disable-while-typing
#    value: 'false'
#  - key: /org/cinnamon/settings-daemon/peripherals/touchpad/horizontal-scrolling
#    value: 'true'
#  - key: /org/cinnamon/settings-daemon/peripherals/touchpad/motion-acceleration
#    value: 6.5696721311475406
#  - key: /org/cinnamon/settings-daemon/peripherals/touchpad/motion-threshold
#    value: 1
  - key: /org/cinnamon/settings-daemon/plugins/xsettings/menus-have-icons
    value: 'true'
  - key: /org/cinnamon/sounds/login-enabled
    value: 'false'
  - key: /org/cinnamon/sounds/logout-enabled
    value: 'false'
  - key: /org/cinnamon/sounds/notification-enabled
    value: 'false'
  - key: /org/cinnamon/desktop/notifications/bottom-notifications
    value: 'true'
  - key: /org/cinnamon/theme/name
    value: "'Numix-Cinnamon'"
  - key: /org/gnome/libgnomekbd/desktop/default-group
    value: 0
  - key: /org/gnome/libgnomekbd/desktop/group-per-window
    value: 'true'
  - key: /org/gnome/libgnomekbd/keyboard/layouts
    value: "['us', 'ru']"
  - key: /org/gnome/libgnomekbd/keyboard/options
    value: "['grp\tgrp:caps_toggle', 'grp_led\tgrp_led:caps']"
  - key: /org/nemo/compact-view/default-zoom-level
    value: "'small'"
  - key: /org/nemo/icon-view/default-zoom-level
    value: "'small'"
  - key: /org/nemo/desktop/computer-icon-visible
    value: 'true'
  - key: /org/nemo/desktop/home-icon-visible
    value: 'true'
  - key: /org/nemo/desktop/trash-icon-visible
    value: 'true'
  - key: /org/nemo/desktop/volumes-visible
    value: 'true'
  - key: /org/nemo/preferences/confirm-trash
    value: 'false'
  - key: /org/nemo/preferences/default-folder-viewer
    value: "'list-view'"
  - key: /org/nemo/preferences/executable-text-activation
    value: "'display'"
  - key: /org/nemo/preferences/show-home-icon-toolbar
    value: 'true'
  - key: /org/nemo/preferences/show-location-entry
    value: 'true'
  - key: /org/nemo/preferences/show-new-folder-icon-toolbar
    value: 'true'
  - key: /org/nemo/preferences/show-open-in-terminal-toolbar
    value: 'true'
  - key: /org/nemo/preferences/show-reload-icon-toolbar
    value: 'true'
  - key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom0/binding
    value: "['<Shift><Super>g']"
  - key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom0/command
    value: "'geany'"
  - key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom0/name
    value: "'geany'"
  #  - key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom1/binding
  #    value: "['<Shift><Super>c']"
  #  - key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom1/command
  #    value: "'steam-native steam://rungameid/730'"
  #  - key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom1/name
  #    value: "'CS GO'"
  #  - key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom2/binding
  #    value: "['<Primary><Shift><Super>m']"
  #  - key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom2/command
  #    value: "'$HOME/scripts/monitor_is_back.sh'"
  #  - key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom2/name
  #    value: "'Monitor is back'"
  #  - key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom3/binding
  #    value: "['<Shift><Super>b']"
  #  - key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom3/command
  #    value: "'tor-browser'"
  #  - key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom3/name
  #    value: "'Tor Browser'"
  - key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom4/binding
    value: "['Calculator']"
  - key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom4/command
    value: "'galculator'"
  - key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom4/name
    value: "'calc'"
  - key: /org/cinnamon/desktop/keybindings/custom-list
    value: "['custom0', 'custom4']"
