---
- name: Install console utilities
  community.general.pacman:
    name:
      - arch-install-scripts
      - docker
      - docker-compose
      - htop
      - lshw
      - man-db
      - mc
      - nmap
      - rsync
      - screen
      - wget
      - xz
  become: true
