---
- name: Install cinnamon
  become: true
  become_user: "{{ aur_user }}"
  kewlfft.aur.aur:
    name:
      - adwaita-icon-theme
      - bluez
      - capitaine-cursors
      - cinnamon
      - faenza-icon-theme
      - file-roller
      - galculator
      - gnome-terminal
      - nemo
      - nemo-fileroller
      - network-manager-applet
      - p7zip
      - unrar
      - xclip
