---
- name: Create users
  ansible.builtin.user:
    name: "{{ user.username }}"
    password: "{{ user.password | ansible.builtin.password_hash(salt=inventory_hostname) }}"
    uid: "{{ user.uid }}"
    groups: "{{ user.groups }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: user
