---
- name: Copy systemd unit file
  ansible.builtin.copy:
    src: reset-bluetooth.service
    dest: /etc/systemd/system
    mode: "0644"
  notify: Systemd_daemon_reload

- name: Enable service
  ansible.builtin.systemd_service:
    name: reset-bluetooth.service
    enabled: true
