$ANSIBLE_VAULT;1.1;AES256
33303434313865333361643438643738616435663138343161303265643534623536313062303165
3634656364356232363531656134633835373032646166300a363132313036633463393539353531
37343165616634363530333731333234383635323363383263653661313965613137663264306238
6336353135343233350a636665653032623339393832366230326330636234633864306135643839
66646433386231313938643064363630633034653432616562303330373762656265666466633031
64636630656530396265316264343734366334366166636465326531643261363662653964373438
61373839633637633963666132303331323634376361363539636566383734356466613535323336
36656263646339376162
