---
install_packages_arch:
  aur:
    - gnome-keyring
    - gnome-screenshot
    - gpicview-gtk3
    - libreoffice-fresh
    - nextcloud-client
    - pinta
    - remmina
    - slack-desktop
    - smplayer
    - pycharm
